{ host, ... }:

let
  inherit (host) hostname;
  inherit (builtins) readFile pathExists;
  extra_config = (
    if pathExists ./${hostname}
    then readFile ./${hostname}
    else ""
  );
in
{
  home.file.i3-config = {
    target = ".config/i3/config";
    text = ''
      # vi: ft=i3config

      # Auto-generated by home-manager

      ${extra_config}
      ${builtins.readFile ./base}
    '';
  };
}
