{ hostname, configuration ? "single" }:

let
  inherit (builtins) readFile pathExists;
  extra_config = (
    if pathExists ./${hostname}
    then readFile ./${hostname}
    else ""
  );
  text = ''
    # vi: ft=i3config

    # Auto-generated by home-manager

    ${extra_config}
    ${builtins.readFile ./base}
  '';
in
{
  target = ".config/i3/config";
  inherit text;
}
