# [build-system]
# requires = ["setuptools"]

[project]
name = "ci"
version = "0.0.0"
description = "Tools for operating Denbeigh's CI"
dependencies = ["click", "jsonschema"]

[project.scripts]
ci = "ci.__main__:__main__"

[tool.setuptools.packages.find]
include = ["ci*"]
