{ config, lib, ... }:

{
  options =
    let
      inherit (config.denbeigh) graphical isNixOS;
      inherit (lib) mkOption types;
    in
    {
      denbeigh.i3.enable = mkOption {
        type = types.bool;
        default = graphical;
        description = "Whether to install and manage i3 config";
      };
    };

  config =
    let
      inherit (lib) mkIf;
      cfg = config.denbeigh.i3;
    in
    mkIf cfg.enable {
      home.file.i3-config =
        let
          inherit (config.denbeigh) hostname;
          inherit (builtins) readFile pathExists;
          extra_config = (
            if pathExists ./${hostname}
            then readFile ./${hostname}
            else ""
          );
        in
        {
          target = ".config/i3/config";
          text = ''
            # vi: ft=i3config

            # Auto-generated by home-manager

            ${extra_config}
            ${builtins.readFile ./base}
          '';
        };
    };
}
